spring.application.name=productor-kafka
# Configuraciones para obtener mas informacion en el log
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG


#Configurciones Kafka
spring.kafka.bootstrap-servers=44.207.126.62:9093,44.207.126.62:9095,44.207.126.62:9097
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#Configuraciones OAuth Tenanat
azure.oauth2.client-id=a4d0c66a-ba7d-4618-9475-ad2d6bd54a6e
azure.oauth2.client-secret=E3q8Q~_bss~fRZIuQLmL8I.BGvWt0faj7UApCbA6
azure.oauth2.tenant-id=9abd8f58-bea4-4ed2-a03b-8b93edc87250
azure.oauth2.scope=https://azurecn2.onmicrosoft.com/a4d0c66a-ba7d-4618-9475-ad2d6bd54a6e/.default
azure.oauth2.token-url=https://login.microsoftonline.com/${azure.oauth2.tenant-id}/oauth2/v2.0/token

#configuraciones de server
server.port=8080